# Generated by Django 3.2.16 on 2024-12-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit_measure',
            new_name='measurement_unit',
        ),
    ]
