# Generated by Django 3.2.16 on 2024-12-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_rename_unit_measure_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='coocking_time',
            field=models.IntegerField(verbose_name='Время приготовления(мин)'),
        ),
    ]
