# Generated by Django 3.2.16 on 2025-02-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250113_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='users/', verbose_name='Фото профиля'),
        ),
    ]
