version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    image: vitsman/foodgram-frontend:latest
    env_file: .env
    build: ../frontend
    command: cp -r /app/result_build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  
  backend:
    image: vitsman/foodgram_back:latest
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "8081:80"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_volume:/staticfiles/
      - media_volume:/media/
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  static_value:
  media_value:
  data_value: