version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: vitsman/foodgram_back:latest
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media        
      - ./backend_static/:/backend_static
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: vitsman/foodgram-frontend:latest
    volumes:
      - static_volume:/app/build

  nginx:
    image: nginx:1.25.4-alpine
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - static_volume:/var/www/html/static
      - media_volume:/var/www/html/media
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - ./backend_static:/var/www/html/static_back
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
